apiVersion: v1
kind: Pod
metadata:
  name: dsv-bench
  namespace: default
  labels:
    app: dsv-bench
spec:
  containers:
  - name: dsv-bench
    image: baseten/trtllm-1.3.0rc3:arm-release_bolt_632c039ae_overlay2512
    imagePullPolicy: IfNotPresent
    command:
    - /bin/bash
    - -c
    - |
      apt update && apt install -y vim git git-lfs curl

      cd /root
      git clone https://github.com/pankajroark/nvl72-dsv-bench.git
      cd nvl72-dsv-bench
      tar -xvf synthetic_8192_512_same_prompt.tar.gz

      trtllm-bench \
        --model nvidia/DeepSeek-R1-NVFP4 \
        throughput \
        --tp 4 \
        --ep 2 \
        --extra_llm_api_options extra_llm_api_options_single_node_agg.yaml \
        --backend pytorch \
        --dataset synthetic_8192_512_same_prompt.txt \
        --warmup 1 \
        --eos_id -1

      sleep infinity
    env:
    resources:
      limits:
        memory: 384Gi
        nvidia.com/gpu: 4
      requests:
        cpu: "16"
        memory: 128Gi
        nvidia.com/gpu: 4

    volumeMounts:
    - mountPath: /root/.cache/huggingface
      name: huggingface-cache
    - mountPath: /dev/shm
      name: shm
  restartPolicy: Always
  nodeSelector:
    kubernetes.io/hostname: p02-r02-cp07
  tolerations:
  - effect: NoSchedule
    key: nvidia.com/gpu
    operator: Exists
  volumes:
  - name: huggingface-cache
    hostPath:
      path: /scratch/cluster-model-performance/huggingface
      type: DirectoryOrCreate
  - name: shm
    emptyDir:
      medium: Memory
      sizeLimit: 8Gi